### ISSUE TITLE
mingw64/mingw-w64-x86_64-python2-numpy is broken

### ISSUE THREAD

**Issue by not-a-user** [msys2/msys2#53]
To reproduce

	pacman -S mingw64/mingw-w64-x86_64-python2-numpy
	/mingw64/bin/python2 -c 'import numpy'

output

	Traceback (most recent call last):
	  File "<string>", line 1, in <module>
	  File "C:/msys64/mingw64/lib/python2.7/site-packages/numpy/__init__.py", line 142, in <module>
	    from . import add_newdocs
	  File "C:/msys64/mingw64/lib/python2.7/site-packages/numpy/add_newdocs.py", line 13, in <module>
	    from numpy.lib import add_newdoc
	  File "C:/msys64/mingw64/lib/python2.7/site-packages/numpy/lib/__init__.py", line 8, in <module>
	    from .type_check import *
	  File "C:/msys64/mingw64/lib/python2.7/site-packages/numpy/lib/type_check.py", line 11, in <module>
	    import numpy.core.numeric as _nx
	  File "C:/msys64/mingw64/lib/python2.7/site-packages/numpy/core/__init__.py", line 26, in <module>
	    raise ImportError(msg)
	ImportError:
	Importing the multiarray numpy extension module failed.  Most
	likely you are trying to import a failed build of numpy.
	If you're working with a numpy git repo, try `git clean -xdf` (removes all
	files not under version control).  Otherwise reinstall numpy.

	Original error was: DLL load failed: The specified module could not be found.

I did a new install including a full upgrade today (2017-07-05).

version numbers

	Name            : mingw-w64-x86_64-python2-numpy
	Version         : 1.13.0-1

**Comment by jvernonc** [comment]
I have tried to get the latest numpy and scipy stack to work in mingw64 for both python 2 and 3 without any success.  Multiple updates and a complete clean re-install within the last week.  For me, both numpy and scipy can be imported okay.  However, python2-numpy fails about 10 tests (most look like precision mismatches, there is an array sizing one that is a concern).  

python2-scipy fails with errors similar to your numpy one, different message but failure to find a DLL.  We may both be missing a windows run-time dll that the building machine had (likely a runtime from a recent MSVC).  That scipy can be imported, but has multiple failures when running tests using the old style, interactively, i.e.
>>>import module
>>>module.test('full')
because modules can not be loaded properly due to missing DLLs.  

Those tests do nothing for python3-numpy in my install.  It seems to execute fine, but runs 0 actual tests.  python3-scipy dies with missing DLLs as soon as 'special' or any other module requiring it is imported.
